### ISSUE TITLE
broken for node < v.2.3.0

### ISSUE THREAD

**Issue by mmraff** [jonschlinkert/expand-tilde#2]
The package.json lists '"engines": { "node": ">=0.10.0" }', yet uses a method os.homedir() that doesn't exist in 0.10.x or 0.12.x; in fact the node.js API documentation says "Added in: v2.3.0".
Recommended support module: os-homedir

**Comment by jonschlinkert** [comment]
Thanks for the issue. 

@doowb does your lib fix this?

**Comment by doowb** [comment]
yes. I can update this lib to use `homedir-polyfill`

**Comment by doowb** [comment]
published in 2.0.2
